### ISSUE TITLE
Does not install

### ISSUE THREAD

**Issue by marcusorjames** [samu/git-diff-details#23] opened 2015-04-30 10:55 UTC
Simply does not install :(

npm ERR! node v0.10.35
npm ERR! npm  v2.5.1
npm ERR! code ELIFECYCLE

npm ERR! oniguruma@4.2.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the oniguruma@4.2.0 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the oniguruma package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls oniguruma
npm ERR! There is likely additional logging output above.

**Comment by samu** [comment] 2015-05-01 10:44
Can you give some additional info on your environment? OS, Atom version, etc.

**Comment by marcusorjames** [comment] 2015-05-08 13:27
Sure OS is windows 8.1, Atom version 0.198

**Comment by rafael25** [comment] 2015-07-03 09:14
Same here
Atom 1.0 on Linux 

```
> oniguruma@4.2.2 install /tmp/apm-install-dir-11563-18380-pmvrqx/node_modules/git-diff-details/node_modules/highlights/node_modules/first-mate/node_modules/oniguruma                                                                                                                                      
> node-gyp rebuild                                                                                                                                    


gyp ERR! configure error                                                                                                                              
gyp ERR! stack Error: Python executable "python" is v3.4.3, which is not supported by gyp.                                                            
gyp ERR! stack You can pass the --python switch to point to Python >= v2.5.0 & < 3.0.0.                                                               
gyp ERR! stack     at failPythonVersion (/home/rafael/App/atom/usr/share/atom/resources/app/apm/node_modules/npm/node_modules/node-gyp/lib/configure.js:108:14)                                                                                                                                             
gyp ERR! stack     at /home/rafael/App/atom/usr/share/atom/resources/app/apm/node_modules/npm/node_modules/node-gyp/lib/configure.js:97:9             
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:656:7)                                                                               
gyp ERR! stack     at ChildProcess.emit (events.js:98:17)                                                                                             
gyp ERR! stack     at maybeClose (child_process.js:766:16)                                                                                            
gyp ERR! stack     at Socket.<anonymous> (child_process.js:979:11)                                                                                    
gyp ERR! stack     at Socket.emit (events.js:95:17)                                                                                                   
gyp ERR! stack     at Pipe.close (net.js:466:12)                                                                                                      
gyp ERR! System Linux 4.0.7-2-ARCH                                                                                                                    
gyp ERR! command "node" "/home/rafael/App/atom/usr/share/atom/resources/app/apm/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"     
gyp ERR! cwd /tmp/apm-install-dir-11563-18380-pmvrqx/node_modules/git-diff-details/node_modules/highlights/node_modules/first-mate/node_modules/oniguruma
gyp ERR! node -v v0.10.35
gyp ERR! node-gyp -v v1.0.2
gyp ERR! not ok 
npm ERR! Linux 4.0.7-2-ARCH
npm ERR! argv "/home/rafael/App/atom/usr/share/atom/resources/app/apm/bin/node" "/home/rafael/App/atom/usr/share/atom/resources/app/apm/node_modules/npm/bin/npm-cli.js" "--globalconfig" "/home/rafael/.atom/.apm/.apmrc" "--userconfig" "/home/rafael/.atom/.apmrc" "install" "/tmp/d-11563-18380-o67ovm/package.tgz" "--target=0.22.0" "--arch=x64"
npm ERR! node v0.10.35
npm ERR! npm  v2.5.1
npm ERR! code ELIFECYCLE

npm ERR! oniguruma@4.2.2 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the oniguruma@4.2.2 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the oniguruma package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls oniguruma
npm ERR! There is likely additional logging output above.

```

**Comment by baivong** [comment] 2015-07-07 05:41
I also had this error.
I'm use:
* windows 8.1
* Atom 1.0.0
* node 0.12.2
* npm 2.7.4
* python 2.7.9

```
> oniguruma@4.2.2 install C:\Users\le\AppData\Local\Temp\apm-install-dir-11567-8944-ng7ex5\node_modules\git-diff-details\node_modules\highlights\node_modules\first-mate\node_modules\oniguruma
> node-gyp rebuild


C:\Users\le\AppData\Local\Temp\apm-install-dir-11567-8944-ng7ex5\node_modules\git-diff-details\node_modules\highlights\node_modules\first-mate\node_modules\oniguruma>node "C:\Users\le\AppData\Local\atom\app-1.0.0\resources\app\apm\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild 

Traceback (most recent call last):
  File "C:\Users\le\AppData\Local\atom\app-1.0.0\resources\app\apm\node_modules\npm\node_modules\node-gyp\gyp\gyp_main.py", line 15, in <module>
    import gyp
  File "C:\Users\le\AppData\Local\atom\app-1.0.0\resources\app\apm\node_modules\npm\node_modules\node-gyp\gyp\pylib\gyp\__init__.py", line 8, in <module>
    import gyp.input
  File "C:\Users\le\AppData\Local\atom\app-1.0.0\resources\app\apm\node_modules\npm\node_modules\node-gyp\gyp\pylib\gyp\input.py", line 15, in <module>
    import multiprocessing
  File "C:\python27\lib\multiprocessing\__init__.py", line 84, in <module>
    import _multiprocessing
ImportError: DLL load failed: %1 is not a valid Win32 application.
gypnpm ERR! Windows_NT 6.2.9200
npm ERR! argv "C:\\Users\\le\\AppData\\Local\\atom\\app-1.0.0\\resources\\app\\apm\\bin\\\\node.exe" "C:\\Users\\le\\AppData\\Local\\atom\\app-1.0.0\\resources\\app\\apm\\node_modules\\npm\\bin\\npm-cli.js" "--globalconfig" "C:\\Users\\le\\.atom\\.apm\\.apmrc" "--userconfig" "C:\\Users\\le\\.atom\\.apmrc" "install" "C:\\Users\\le\\AppData\\Local\\Temp\\d-11567-8944-x5wwly\\package.tgz" "--target=0.22.0" "--arch=ia32"
npm ERR! node v0.10.35
npm ERR! npm  v2.5.1
npm ERR! code ELIFECYCLE

npm ERR! oniguruma@4.2.2 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the oniguruma@4.2.2 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the oniguruma package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls oniguruma
npm ERR! There is likely additional logging output above.
```

**Comment by samu** [comment] 2015-07-07 09:32
I can't reproduce this error on my machine, so i'll need help from you guys. 

You can install the package via apm directly, try this:

`apm install git-diff-details --verbose`

Hopefully this will give some more info.

Also run this:

`apm --version`

My output is:

```
apm  1.0.1
npm  2.5.1
node 0.10.35
python 2.7.6
git 2.3.2
```

**Comment by rafael25** [comment] 2015-07-09 09:53
Sure
My output from `apm --version`

```
apm  1.0.1
npm  2.5.1
node 0.10.35
python 3.4.3
git 2.4.5
```

and from `apm install git-diff-details --verbose` in folowing gist

https://gist.github.com/rafael25/bf59167d4399af0359af

**Comment by rafael25** [comment] 2015-07-09 10:01
may it be due to this?
`gyp ERR! stack Error: Python executable "python" is v3.4.3, which is not supported by gyp.`
at line 2451
https://gist.github.com/rafael25/bf59167d4399af0359af#file-git_diff_details_error-log-L2451

**Comment by MattiJarvinen-BA** [comment] 2015-07-22 07:01
Same here... error is thrown from settings-view and is said to be fixed in next Atom release https://github.com/atom/settings-view/issues/594

**Atom Version**: 1.0.2
**System**: Microsoft Windows 8.1
**Thrown From**: [settings-view](https://github.com/atom/settings-view) package, v0.211.0


### Stack Trace

Uncaught TypeError: Cannot read property 'message' of undefined

```
At C:\Users\matti_000\AppData\Local\atom\app-1.0.2\resources\app.asar\node_modules\settings-view\lib\error-view.js:56

TypeError: Cannot read property 'message' of undefined
  at ErrorView.module.exports.ErrorView.initialize (C:\Users\matti_000\AppData\Local\atom\app-1.0.2\resources\app.asar\node_modules\settings-view\lib\error-view.js:56:21)
  at ErrorView.View (C:\Users\matti_000\AppData\Local\atom\app-1.0.2\resources\app.asar\node_modules\atom-space-pen-views\node_modules\space-pen\lib\space-pen.js:184:25)
  at new ErrorView (C:\Users\matti_000\AppData\Local\atom\app-1.0.2\resources\app.asar\node_modules\settings-view\lib\error-view.js:14:46)
  at C:\Users\matti_000\AppData\Local\atom\app-1.0.2\resources\app.asar\node_modules\settings-view\lib\installed-packages-panel.js:179:44
  at Emitter.module.exports.Emitter.emit (C:\Users\matti_000\AppData\Local\atom\app-1.0.2\resources\app.asar\node_modules\event-kit\lib\emitter.js:82:11)
  at PackageManager.module.exports.PackageManager.emitPackageEvent (C:\Users\matti_000\AppData\Local\atom\app-1.0.2\resources\app.asar\node_modules\settings-view\lib\package-manager.js:579:27)
  at C:\Users\matti_000\AppData\Local\atom\app-1.0.2\resources\app.asar\node_modules\settings-view\lib\package-manager.js:359:17
  at C:\Users\matti_000\AppData\Local\atom\app-1.0.2\resources\app.asar\node_modules\settings-view\lib\package-manager.js:384:20
  at exit (C:\Users\matti_000\AppData\Local\atom\app-1.0.2\resources\app.asar\node_modules\settings-view\lib\package-manager.js:59:16)
  at triggerExitCallback (C:\Users\matti_000\AppData\Local\atom\app-1.0.2\resources\app.asar\src\buffered-process.js:213:47)
  at C:\Users\matti_000\AppData\Local\atom\app-1.0.2\resources\app.asar\src\buffered-process.js:220:18
  at Socket.<anonymous> (C:\Users\matti_000\AppData\Local\atom\app-1.0.2\resources\app.asar\src\buffered-process.js:98:18)
  at emitOne (events.js:82:20)
  at Socket.emit (events.js:166:7)
  at Pipe.close (net.js:464:12)

```

### Commands

```
     -0:28 core:backspace (atom-text-editor.editor.mini.is-focused)
     -0:24.8.0 core:confirm (atom-text-editor.editor.mini.is-focused)
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-material-ui",
      "base16-tomorrow-dark-theme"
    ],
    "autoHideMenuBar": true
  }
}
```

### Installed Packages

```coffee
# User
atom-material-ui, v0.5.9
file-icons, v1.5.8
git-log, v0.4.1
line-diff-details, v1.1.2
minimap, v4.12.0
minimap-codeglance, v0.2.1
project-manager, v1.15.11
symbols-tree-view, v0.9.3

# Dev
No dev packages
```

**Comment by Evmorov** [comment] 2015-07-29 13:55
@marcusorjames Previous messages aren't connected with settings-view

I had the same problem on Windows. I've managed to install this package using advice from http://stackoverflow.com/questions/21365714/nodejs-error-installing-with-npm.

Also, many packages suffer from this error. The reason is a huge chain of dependencies. Some packages require build tools and/or Python.

**Comment by piotr-cz** [comment] 2015-07-29 14:46
uhm, so for Windows 8 I'd need to install Pyton and MS Visual Studio C++ 2012 :/

**Comment by samu** [comment] 2015-07-30 08:36
@Evmorov Thanks for pointing this out! I'll keep this issue open, but as it seems i can't do anything right now to get this package working on specific systems... Sorry :(

**Comment by piotr-cz** [comment] 2015-07-30 08:41
is there a chance of dropping _node-gyp_ which i an indirect dependency?

**Comment by samu** [comment] 2015-07-30 09:12
It's the highlights package that has a dependency to node-gyp. Unfortunately i can't remove that.

**Comment by samu** [comment] 2015-08-07 14:43
You might want to try the following (according to [this issue](https://github.com/atom/node-oniguruma/issues/18)):

`PYTHON=python2 apm install git-diff-details`

**Comment by rafael25** [comment] 2015-08-08 06:41
Thank you @samu 
it works smoothly

**Comment by ethali** [comment] 2015-09-07 15:09
And under Windows?
PYTHON=python2 apm install git-diff-details doesn't work.
Thank you.

**Comment by hnsl** [comment] 2015-09-18 10:00
Uninstalling and reinstalling fixed the problem for me.

I also ran a `sudo npm install --unsafe-perm --verbose -g oniguruma` before uninstalling which could have helped.

**Comment by hnsl** [comment] 2015-09-18 16:47
Nope, it's back, didn't' fix the problem. Uninstalled for now.

**Comment by UltCombo** [comment] 2015-09-19 06:31
It works fine on OS X Yosemite for me. Reinstall the package through the Atom interface, it will then report an incompatible native module as the `oniguruma` dependency has an install script that calls `node-gyp rebuild` directly which seems to target your environment's Node version instead of Atom's. Clicking in the "rebuild dependencies" after the install fixed the issue for me, though.

Now I'm having issues on Windows 10, looks like it is because I have VS2010 and oniguruma requires at least VS2012 apparently.

**Comment by UltCombo** [comment] 2015-09-19 08:06
I've installed VS2015 (with the "Common Tools for Visual C++ 2015" feature) and reinstalling `git-diff-details` worked fine now.

**Comment by shadoWalker89** [comment] 2015-10-21 08:05
I get this error while i try to install

OS : windows 8.1
Atom : 1.0.19

Installing “git-diff-details@undefined” failed.Hide output…

> oniguruma@4.2.4 install C:\Users\melek\AppData\Local\Temp\apm-install-dir-115921-2692-f6fjih\node_modules\git-diff-details\node_modules\highlights\node_modules\first-mate\node_modules\oniguruma
> node-gyp rebuild


C:\Users\melek\AppData\Local\Temp\apm-install-dir-115921-2692-f6fjih\node_modules\git-diff-details\node_modules\highlights\node_modules\first-mate\node_modules\oniguruma>if not defined npm_config_node_gyp (node "C:\Users\melek\AppData\Local\atom\app-1.0.19\resources\app\apm\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node  rebuild ) 

npm ERR! Windows_NT 6.2.9200
npm ERR! argv "C:\\Users\\melek\\AppData\\Local\\atom\\app-1.0.19\\resources\\app\\apm\\bin\\node.exe" "C:\\Users\\melek\\AppData\\Local\\atom\\app-1.0.19\\resources\\app\\apm\\node_modules\\npm\\bin\\npm-cli.js" "--globalconfig" "C:\\Users\\melek\\.atom\\.apm\\.apmrc" "--userconfig" "C:\\Users\\melek\\.atom\\.apmrc" "install" "C:\\Users\\melek\\AppData\\Local\\Temp\\d-115921-2692-3bvryo\\package.tgz" "--target=0.30.7" "--arch=ia32" "--msvs_version=2012"
npm ERR! node v0.10.40
npm ERR! npm  v2.13.3
npm ERR! code ELIFECYCLE

npm ERR! oniguruma@4.2.4 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the oniguruma@4.2.4 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the oniguruma package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls oniguruma
npm ERR! There is likely additional logging output above.

**Comment by Kisty** [comment] 2015-11-04 15:54
Got a similar issue on Atom 1.1.0, Win 7 Professional 64-bit

```
> oniguruma@5.1.2 install C:\Users\TimKist\AppData\Local\Temp\apm-install-dir-115104-13240-2vdyoj\node_modules\git-diff-details\node_modules\highlights\node_modules\first-mate\node_modules\oniguruma
> node-gyp rebuild


C:\Users\TimKist\AppData\Local\Temp\apm-install-dir-115104-13240-2vdyoj\node_modules\git-diff-details\node_modules\highlights\node_modules\first-mate\node_modules\oniguruma>if not defined npm_config_node_gyp (node "C:\Users\TimKist\AppData\Local\atom\app-1.1.0\resources\app\apm\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node  rebuild ) 
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
MSBUILD : error MSB3428: Could not load the Visual C++ component "VCBuild.exe". To fix this, 1) install the .NET Framework 2.0 SDK, 2) install Microsoft Visual Studio 2005 or 3) add the location of the component to the system path if it is installed elsewhere.  [C:\Users\TimKist\AppData\Local\Temp\apm-install-dir-115104-13240-2vdyoj\node_modules\git-diff-details\node_modules\highlights\node_modules\first-mate\node_modules\oniguruma\build\binding.sln]

gypnpm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Users\\TimKist\\AppData\\Local\\atom\\app-1.1.0\\resources\\app\\apm\\bin\\node.exe" "C:\\Users\\TimKist\\AppData\\Local\\atom\\app-1.1.0\\resources\\app\\apm\\node_modules\\npm\\bin\\npm-cli.js" "--globalconfig" "C:\\Users\\TimKist\\.atom\\.apm\\.apmrc" "--userconfig" "C:\\Users\\TimKist\\.atom\\.apmrc" "install" "C:\\Users\\TimKist\\AppData\\Local\\Temp\\d-115104-13240-wyl7yg\\package.tgz" "--target=0.30.7" "--arch=ia32"
npm ERR! node v0.10.40
npm ERR! npm  v2.13.3
npm ERR! code ELIFECYCLE

npm ERR! oniguruma@5.1.2 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the oniguruma@5.1.2 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the oniguruma package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls oniguruma
npm ERR! There is likely additional logging output above.
```

**Comment by maxgrass** [comment] 2016-01-20 19:30
Installing “git-diff-details@0.21.0” failed.

> oniguruma@5.1.2 install C:\Users\X\AppData\Local\Temp\apm-install-dir-116020-10960-1e9eqwa\node_modules\git-diff-details\node_modules\highlights\node_modules\first-mate\node_modules\oniguruma
> node-gyp rebuild


C:\Users\X\AppData\Local\Temp\apm-install-dir-116020-10960-1e9eqwa\node_modules\git-diff-details\node_modules\highlights\node_modules\first-mate\node_modules\oniguruma>if not defined npm_config_node_gyp (node "<pathToAtom>atom\app-1.4.0\resources\app\apm\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node  rebuild ) 

gypnpm ERR! Windows_NT 6.2.9200
npm ERR! argv "<pathToAtom>atom\\app-1.4.0\\resources\\app\\apm\\bin\\node.exe" "<pathToAtom>atom\\app-1.4.0\\resources\\app\\apm\\node_modules\\npm\\bin\\npm-cli.js" "--globalconfig" "<pathToAtom>atom\\.atom\\.apm\\.apmrc" "--userconfig" "<pathToAtom>atom\\.atom\\.apmrc" "install" "C:\\Users\\X\\AppData\\Local\\Temp\\d-116020-10960-1ixivoz\\package.tgz" "--target=0.34.5" "--arch=ia32"
npm ERR! node v0.10.40
npm ERR! npm  v2.13.3
npm ERR! code ELIFECYCLE

npm ERR! oniguruma@5.1.2 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the oniguruma@5.1.2 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the oniguruma package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls oniguruma
npm ERR! There is likely additional logging output above.

**Comment by llagerlof** [comment] 2016-02-11 17:16
Same problem here. I have Windows 8 x64 with Atom 1.5.1. The solution @UltCombo provided doesn't worked for me.
However I make this plugin to be installed without errors. I just uninstalled Python 3 and installed the latest Python 2 (Python 2.7.11 x64 in my case).

**Comment by syuilo** [comment] 2016-03-19 02:51
I have same issue.

OS: Windows10
Atom: 1.5.4

Stack trace:
```
> oniguruma@5.1.2 install C:\Users\syuilo\AppData\Local\Temp\apm-install-dir-116219-11860-18m1h50\node_modules\git-diff-details\node_modules\highlights\node_modules\first-mate\node_modules\oniguruma
> node-gyp rebuild


C:\Users\syuilo\AppData\Local\Temp\apm-install-dir-116219-11860-18m1h50\node_modules\git-diff-details\node_modules\highlights\node_modules\first-mate\node_modules\oniguruma>if not defined npm_config_node_gyp (node "C:\Users\syuilo\AppData\Local\atom\app-1.5.4\resources\app\apm\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node  rebuild ) 
���̃\�����[�V�������̃v���W�F�N�g�� 1 �x�� 1 ���r���h���܂��B���s�r���h���L���ɂ����ɂ́A"/m" �X�C�b�`���ǉ����Ă��������B
C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.Cpp.Platform.targets(57,5): error MSB8020: The build tools for v120 (Platform Toolset = 'v120') cannot be found. To build using the v120 build tools, please install v120 build tools.  Alternatively, you may upgrade to the current Visual Studio tools by selecting the Project menu or right-click the solution, and then selecting "Retarget solution". [C:\Users\syuilo\AppData\Local\Temp\apm-install-dir-116219-11860-18m1h50\node_modules\git-diff-details\node_modules\highlights\node_modules\first-mate\node_modules\oniguruma\build\oniguruma.vcxproj]

gypnpm ERR! Windows_NT 6.2.9200
npm ERR! argv "C:\\Users\\syuilo\\AppData\\Local\\atom\\app-1.5.4\\resources\\app\\apm\\bin\\node.exe" "C:\\Users\\syuilo\\AppData\\Local\\atom\\app-1.5.4\\resources\\app\\apm\\node_modules\\npm\\bin\\npm-cli.js" "--globalconfig" "C:\\Users\\syuilo\\.atom\\.apm\\.apmrc" "--userconfig" "C:\\Users\\syuilo\\.atom\\.apmrc" "install" "C:\\Users\\syuilo\\AppData\\Local\\Temp\\d-116219-11860-1cebivr\\package.tgz" "--target=0.34.5" "--arch=ia32" "--msvs_version=2013"
npm ERR! node v0.10.40
npm ERR! npm  v2.13.3
npm ERR! code ELIFECYCLE

npm ERR! oniguruma@5.1.2 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the oniguruma@5.1.2 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the oniguruma package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls oniguruma
npm ERR! There is likely additional logging output above.
```

**Comment by samu** [comment] 2016-03-19 12:57
Version `1.0.0` is out! The dependency to the highlights-package has been dropped, so you should now be able to install the package without any troubles. Also, the package now makes use of the awesome new block decorators (requires atom 1.6.0)!

**Closed by samu** 2016-03-19 12:57 UTC

**Comment by UltCombo** [comment] 2016-03-20 05:22
Fantastic work! :clap:
